// ─── Maps the real .NET GetOrder response into the shape the UI expects ───
//
// Confirmed against OrderResponseModel.cs + OrderRepository.cs — these are
// the EXACT fields the backend returns, no guessing needed. ASP.NET Core's
// default JSON serializer camel-cases the C# property names automatically,
// e.g. C#'s `PoNumber` arrives in the browser as `poNumber`.

export function mapOrderResponse(raw) {
  if (!raw) return null;

  const toPartnerSetupRecord = (entry) => ({
    coCd: entry.coCd ?? entry.CO_CD ?? "—",
    partnerId: entry.partnerId ?? entry.PARTNER_ID ?? "—",
    partnerTypeCd: entry.partnerTypeCd ?? entry.PARTNER_TYPE_CD ?? "—",
    srceSysId: entry.srceSysId ?? entry.SRCE_SYS_ID ?? "—",
    srceSysKeyId: entry.srceSysKeyId ?? entry.SRCE_SYS_KEY_ID ?? "—",
    formatId: entry.formatId ?? entry.FORMAT_ID ?? "—",
    docId: entry.docId ?? entry.DOC_ID ?? "—",
    commuId: entry.commuId ?? entry.COMMU_ID ?? "—",
    internetAddrTxt: entry.internetAddrTxt ?? entry.INTERNET_ADDR_TXT ?? "—",
    dirFlgCd: entry.dirFlgCd ?? entry.DIR_FLG_CD ?? "—",
    sendThruId: entry.sendThruId ?? entry.SEND_THRU_ID ?? "—",
    dataStoreMechId: entry.dataStoreMechId ?? entry.DATA_STORE_MECH_ID ?? "—",
    prcsOptnFlg: entry.prcsOptnFlg ?? entry.PRCS_OPTN_FLG ?? "—",
    batchSplitCnt: entry.batchSplitCnt ?? entry.BATCH_SPLIT_CNT ?? "—",
    ovrdApplBatchId: entry.ovrdApplBatchId ?? entry.OVRD_APPL_BATCH_ID ?? "—",
    freqId: entry.freqId ?? entry.FREQ_ID ?? "—",
    cycleIntvl: entry.cycleIntvl ?? entry.CYCLE_INTVL ?? "—",
    cycStrtTm: entry.cycStrtTm ?? entry.CYC_STRT_TM ?? "—",
    cycEndTm: entry.cycEndTm ?? entry.CYC_END_TM ?? "—",
    cycleLstRunTs: entry.cycleLstRunTs ?? entry.CYCLE_LST_RUN_TS ?? "—",
    actvDt: entry.actvDt ?? entry.ACTV_DT ?? "—",
    deactvDt: entry.deactvDt ?? entry.DEACTV_DT ?? "—",
    holdCd: entry.holdCd ?? entry.HOLD_CD ?? "—",
    lstChgTs: entry.lstChgTs ?? entry.LST_CHG_TS ?? "—",
    lstChgNam: entry.lstChgNam ?? entry.LST_CHG_NAM ?? "—",
    setupNotesTxt: entry.setupNotesTxt ?? entry.SETUP_NOTES_TXT ?? "—",
  });

  const toInPoSwRecord = (entry) => ({
    coCd: entry.coCd ?? entry.CO_CD ?? "—",
    partnerId: entry.partnerId ?? entry.PARTNER_ID ?? "—",
    skipFrTm: entry.skipFrTm ?? entry.SKIP_FR_TM ?? "—",
    skipToTm: entry.skipToTm ?? entry.SKIP_TO_TM ?? "—",
    custPrty: entry.custPrty ?? entry.CUST_PRTY ?? "—",
    ackPoFlg: entry.ackPoFlg ?? entry.ACK_PO_FLG ?? "—",
    ackPromoFlg: entry.ackPromoFlg ?? entry.ACK_PROMO_FLG ?? "—",
    baserateFlg: entry.baserateFlg ?? entry.BASERATE_FLG ?? "—",
    aggCdCpblFlg: entry.aggCdCpblFlg ?? entry.AGG_CD_CPBL_FLG ?? "—",
    preImHoldFlg: entry.preImHoldFlg ?? entry.PRE_IM_HOLD_FLG ?? "—",
    multShpToFlg: entry.multShpToFlg ?? entry.MULT_SHP_TO_FLG ?? "—",
    systemPartsFlg: entry.systemPartsFlg ?? entry.SYSTEM_PARTS_FLG ?? "—",
    voidTaxableFlg: entry.voidTaxableFlg ?? entry.VOID_TAXABLE_FLG ?? "—",
    casepackMsgFlg: entry.casepackMsgFlg ?? entry.CASEPACK_MSG_FLG ?? "—",
    chkCustPrcFlg: entry.chkCustPrcFlg ?? entry.CHK_CUST_PRC_FLG ?? "—",
    distDepthFlg: entry.distDepthFlg ?? entry.DIST_DEPTH_FLG ?? "—",
    airBrSeqFlg: entry.airBrSeqFlg ?? entry.AIR_BR_SEQ_FLG ?? "—",
    brSeqOrideFlg: entry.brSeqOrideFlg ?? entry.BR_SEQ_ORIDE_FLG ?? "—",
    multBrSeqFlg: entry.multBrSeqFlg ?? entry.MULT_BR_SEQ_FLG ?? "—",
    exportBrSeqFlg: entry.exportBrSeqFlg ?? entry.EXPORT_BR_SEQ_FLG ?? "—",
    holdOrderFlg: entry.holdOrderFlg ?? entry.HOLD_ORDER_FLG ?? "—",
    dfltCustNbr: entry.dfltCustNbr ?? entry.DFLT_CUST_NBR ?? "—",
    promoCustNbr: entry.promoCustNbr ?? entry.PROMO_CUST_NBR ?? "—",
    priceCustNbr: entry.priceCustNbr ?? entry.PRICE_CUST_NBR ?? "—",
    instRebatMsgFlg: entry.instRebatMsgFlg ?? entry.INST_REBAT_MSG_FLG ?? "—",
    vlaFlg: entry.vlaFlg ?? entry.VLA_FLG ?? "—",
    multiDistFlg: entry.multiDistFlg ?? entry.MULTI_DIST_FLG ?? "—",
    saveFrtFlg: entry.saveFrtFlg ?? entry.SAVE_FRT_FLG ?? "—",
    saveDistFlg: entry.saveDistFlg ?? entry.SAVE_DIST_FLG ?? "—",
    bestWhseFlg: entry.bestWhseFlg ?? entry.BEST_WHSE_FLG ?? "—",
    singleWhseFlg: entry.singleWhseFlg ?? entry.SINGLE_WHSE_FLG ?? "—",
    prntOrdrFlg: entry.prntOrdrFlg ?? entry.PRNT_ORDR_FLG ?? "—",
    multShpSortSeq: entry.multShpSortSeq ?? entry.MULT_SHP_SORT_SEQ ?? "—",
    maxFutDay: entry.maxFutDay ?? entry.MAX_FUT_DAY ?? "—",
    lstChgTs: entry.lstChgTs ?? entry.LST_CHG_TS ?? "—",
    lstChgNam: entry.lstChgNam ?? entry.LST_CHG_NAM ?? "—",
    clsXFltrTypCd: entry.clsXFltrTypCd ?? entry.CLS_X_FLTR_TYP_CD ?? "—",
    clsSFltrTypCd: entry.clsSFltrTypCd ?? entry.CLS_S_FLTR_TYP_CD ?? "—",
    updCustSkuFlg: entry.updCustSkuFlg ?? entry.UPD_CUST_SKU_FLG ?? "—",
    saveCustPrcFlg: entry.saveCustPrcFlg ?? entry.SAVE_CUST_PRC_FLG ?? "—",
    boBrXferFlg: entry.boBrXferFlg ?? entry.BO_BR_XFER_FLG ?? "—",
    rejOrdrHdrFlg: entry.rejOrdrHdrFlg ?? entry.REJ_ORDR_HDR_FLG ?? "—",
    rejCnsCmpHdrFlg: entry.rejCnsCmpHdrFlg ?? entry.REJ_CNSCMP_HDR_FLG ?? "—",
    ackRptFlg: entry.ackRptFlg ?? entry.ACK_RPT_FLG ?? "—",
    specPrcFlg: entry.specPrcFlg ?? entry.SPEC_PRC_FLG ?? "—",
    euCaptureFlg: entry.euCaptureFlg ?? entry.EU_CAPTURE_FLG ?? "—",
    customCarrFlg: entry.customCarrFlg ?? entry.CUSTOM_CARR_FLG ?? "—",
    cascadeSkuFlg: entry.cascadeSkuFlg ?? entry.CASCADE_SKU_FLG ?? "—",
    autoPoChgFlg: entry.autoPoChgFlg ?? entry.AUTO_PO_CHG_FLG ?? "—",
    clsXHldFlg: entry.clsXHldFlg ?? entry.CLS_X_HLD_FLG ?? "—",
    stStoreOvrRdFlg: entry.stStoreOvrRdFlg ?? entry.ST_STORE_OVRRD_FLG ?? "—",
    rsrvCustNbr: entry.rsrvCustNbr ?? entry.RSRV_CUST_NBR ?? "—",
    rsrvAllowed: entry.rsrvAllowed ?? entry.RSRV_ALLOWED ?? "—",
    rsrvExpirDays: entry.rsrvExpirDays ?? entry.RSRV_EXPIR_DAYS ?? "—",
    configVisibleFlg: entry.configVisibleFlg ?? entry.CONFIG_VISIBLE_FLG ?? "—",
    etaCalcFlg: entry.etaCalcFlg ?? entry.ETA_CALC_FLG ?? "—",
    etaDays: entry.etaDays ?? entry.ETA_DAYS ?? "—",
    addrValidFlg: entry.addrValidFlg ?? entry.ADDR_VALID_FLG ?? "—",
    autoSplitFlg: entry.autoSplitFlg ?? entry.AUTO_SPLIT_FLG ?? "—",
    ordrCancDaysFlg: entry.ordrCancDaysFlg ?? entry.ORDR_CANC_DAYS_FLG ?? "—",
    ordrCancDaysNbr: entry.ordrCancDaysNbr ?? entry.ORDR_CANC_DAYS_NBR ?? "—",
    futOrdrSw: entry.futOrdrSw ?? entry.FUT_ORDR_SW ?? "—",
    ackDelaySw: entry.ackDelaySw ?? entry.ACK_DELAY_SW ?? "—",
    ackDelayHrs: entry.ackDelayHrs ?? entry.ACK_DELAY_HRS ?? "—",
  });

  const order = {
    custCoCd: raw.custCoCd ?? "—",
    custBr: raw.custBr ?? "—",
    custNbr: raw.custNbr ?? "—",
    custSfx: raw.custSfx ?? "—",
    custPoNbr: raw.custPoNbr ?? "—",
    sdqSeqNbr: raw.sdqSeqNbr ?? "—",
    custPoDt: raw.custPoDt ?? "—",
    custPoSeqNbr: raw.custPoSeqNbr ?? "—",
    tagNbr: raw.tagNbr ?? "—",
    relsTagNbr: raw.relsTagNbr ?? "—",
    processUnitTs: raw.processUnitTs ?? "—",
    applId: raw.applId ?? "—",
    xactSet: raw.xactSet ?? "—",
    partnerId: raw.partnerId ?? "—",
    cmbBtchNbr: raw.cmbBtchNbr ?? "—",
    imiAsgdBrNbr: raw.imiAsgdBrNbr ?? "—",
    imiAsgdOrdrNbr: raw.imiAsgdOrdrNbr ?? "—",
    ordrType: raw.ordrType ?? "—",
    ordrCcyCd: raw.ordrCcyCd ?? "—",
    sellrSalesNbr: raw.sellrSalesNbr ?? "—",
    ordrReqShipDt: raw.ordrReqShipDt ?? "—",
    ordrReqDlvyDt: raw.ordrReqDlvyDt ?? "—",
    ordrReqCancDt: raw.ordrReqCancDt ?? "—",
    orideCustPoDt: raw.orideCustPoDt ?? "—",
    ordrEtaDt: raw.ordrEtaDt ?? "—",
    resvInvSw: raw.resvInvSw ?? "—",
    govtPubPrivSw: raw.govtPubPrivSw ?? "—",
    govtPgmType: raw.govtPgmType ?? "—",
    cnsgnSw: raw.cnsgnSw ?? "—",
    slaCode: raw.slaCode ?? "—",
    isDelvFlg: raw.isDelvFlg ?? "—",
    specLblCode: raw.specLblCode ?? "—",
    poGovtTp: raw.poGovtTp ?? "—",
    deptNbr: raw.deptNbr ?? "—",
    byrLoc: raw.byrLoc ?? "—",
    byrCntact: raw.byrCntact ?? "—",
    byrPhnNbr: raw.byrPhnNbr ?? "—",
    byrVndrNbr: raw.byrVndrNbr ?? "—",
    xmitHashTot: raw.xmitHashTot ?? "—",
    xmitTotLines: raw.xmitTotLines ?? "—",
    cfgType: raw.cfgType ?? "—",
    contNbr: raw.contNbr ?? "—",
    labType: raw.labType ?? "—",
    configPoType: raw.configPoType ?? "—",
    stateCd: raw.stateCd ?? "—",
    ordEntryDtTs: raw.ordEntryDtTs ?? "—",
    imiCarCd: raw.imiCarCd ?? "—",
    custCarrCode: raw.custCarrCode ?? "—",
    imiShipVia: raw.imiShipVia ?? "—",
    codAmt: raw.codAmt ?? "—",
    codFeeSwtch: raw.codFeeSwtch ?? "—",
    thrdPtyAct: raw.thrdPtyAct ?? "—",
    boOrideSwtch: raw.boOrideSwtch ?? "—",
    brSeqValu: raw.brSeqValu ?? "—",
    distrbDepth: raw.distrbDepth ?? "—",
    maxXitDays: raw.maxXitDays ?? "—",
    airBrSeqFlg: raw.airBrSeqFlg ?? "—",
    brSeqFlg: raw.brSeqFlg ?? "—",
    multBrSeqFlg: raw.multBrSeqFlg ?? "—",
    exptBrSeqFlg: raw.exptBrSeqFlg ?? "—",
    saveFrtFlg: raw.saveFrtFlg ?? "—",
    saveDistFlg: raw.saveDistFlg ?? "—",
    singleWhse: raw.singleWhse ?? "—",
    prntOrdrFlg: raw.prntOrdrFlg ?? "—",
    baserateFlg: raw.baserateFlg ?? "—",
    multDistrbFlg: raw.multDistrbFlg ?? "—",
    nbrOfWhse: raw.nbrOfWhse ?? "—",
    ordShFr: raw.ordShFr ?? "—",
    shipFlg: raw.shipFlg ?? "—",
    ordSt: raw.ordSt ?? "—",
    ordrRejFlg: raw.ordrRejFlg ?? "—",
    dmdBr: raw.dmdBr ?? "—",
    processDt: raw.processDt ?? "—",
    processTm: raw.processTm ?? "—",
    terms: raw.terms ?? "—",
    ccyRate: raw.ccyRate ?? "—",
    dropMsg: raw.dropMsg ?? "—",
    ordrHasErrs: raw.ordrHasErrs ?? "—",
    taxFlg: raw.taxFlg ?? "—",
    euName: raw.euName ?? "—",
    euAttn: raw.euAttn ?? "—",
    euAddr1: raw.euAddr1 ?? "—",
    euAddr2: raw.euAddr2 ?? "—",
    euAddr3: raw.euAddr3 ?? "—",
    euAddr4: raw.euAddr4 ?? "—",
    euCity: raw.euCity ?? "—",
    euState: raw.euState ?? "—",
    euZip: raw.euZip ?? "—",
    euCtry: raw.euCtry ?? "—",
    euTax: raw.euTax ?? "—",
    euCntact: raw.euCntact ?? "—",
    euPhnNbr: raw.euPhnNbr ?? "—",
    euPhnNbrExt: raw.euPhnNbrExt ?? "—",
    euFaxNbr: raw.euFaxNbr ?? "—",
    euEmail: raw.euEmail ?? "—",
    euResaleRslr: raw.euResaleRslr ?? "—",
    euRefNbr: raw.euRefNbr ?? "—",
    stName: raw.stName ?? "—",
    stAttn: raw.stAttn ?? "—",
    stAttn2: raw.stAttn2 ?? "—",
    stPhoneNbr: raw.stPhoneNbr ?? "—",
    stAddr1: raw.stAddr1 ?? "—",
    stAddr2: raw.stAddr2 ?? "—",
    stAddr3: raw.stAddr3 ?? "—",
    stAddr4: raw.stAddr4 ?? "—",
    stCity: raw.stCity ?? "—",
    stState: raw.stState ?? "—",
    stZip: raw.stZip ?? "—",
    stCtry: raw.stCtry ?? "—",
    stPtnrStoreNbr: raw.stPtnrStoreNbr ?? "—",
    stImiStSuf: raw.stImiStSuf ?? "—",
    custRefNbr: raw.custRefNbr ?? "—",
    custRefNbr2: raw.custRefNbr2 ?? "—",
    ordRefNbr: raw.ordRefNbr ?? "—",
    ordRelsNbr: raw.ordRelsNbr ?? "—",
    billToRefNbr: raw.billToRefNbr ?? "—",
    imiRefNbr: raw.imiRefNbr ?? "—",
    endCustActNbr: raw.endCustActNbr ?? "—",
    endCustOrdNbr: raw.endCustOrdNbr ?? "—",
    endCustPoNbr: raw.endCustPoNbr ?? "—",
    custVdrNbr: raw.custVdrNbr ?? "—",
    endCustRefNbr: raw.endCustRefNbr ?? "—",
    vlaRlsdFlg: raw.vlaRlsdFlg ?? "—",
    vlaRlsdId: raw.vlaRlsdId ?? "—",
    vlaRlsdDtTm: raw.vlaRlsdDtTm ?? "—",
    vlaEtaDt: raw.vlaEtaDt ?? "—",
    vlaRejectReason: raw.vlaRejectReason ?? "—",
    vlaEuNbr: raw.vlaEuNbr ?? "—",
    vlaAuthNbr: raw.vlaAuthNbr ?? "—",
    frghtOutCode: raw.frghtOutCode ?? "—",
    govtSolctnNbr: raw.govtSolctnNbr ?? "—",
    specFormSwtch: raw.specFormSwtch ?? "—",
    allLinesConfig: raw.allLinesConfig ?? "—",
    db2CrtTs: raw.db2CrtTs ?? "—",
    vlaType: raw.vlaType ?? "—",
    splitName1: raw.splitName1 ?? "—",
    splitName2: raw.splitName2 ?? "—",
    eoEdiCd: raw.eoEdiCd ?? "—",
    badAddrSwtch: raw.badAddrSwtch ?? "—",
    fulfilOrderFlg: raw.fulfilOrderFlg ?? "—",
    preProcsRpt: raw.preProcsRpt ?? "—",
    mastVendNbr: raw.mastVendNbr ?? "—",
    rslrEmail: raw.rslrEmail ?? "—",
    rslrFax: raw.rslrFax ?? "—",
    rslrLotusId: raw.rslrLotusId ?? "—",
    imiBtSuf: raw.imiBtSuf ?? "—",
    busRegnCd: raw.busRegnCd ?? "—",
    holdCd: raw.holdCd ?? "—",
    xdockDistCtr: raw.xdockDistCtr ?? "—",
    dvFlg: raw.dvFlg ?? "—",
    eddFlg: raw.eddFlg ?? "—",
    vendQotNbr: raw.vendQotNbr ?? "—",
    stEmail: raw.stEmail ?? "—",
    custinLicVlidCd: raw.custinLicVlidCd ?? "—",
    recalcLicVlidCd: raw.recalcLicVlidCd ?? "—",
    custFrtFwrdFlg: raw.custFrtFwrdFlg ?? "—",
    imFrtFwrdFlg: raw.imFrtFwrdFlg ?? "—",
    serviceInd: raw.serviceInd ?? "—",
    serviceLevel: raw.serviceLevel ?? "—",
    carrierAccount: raw.carrierAccount ?? "—",
    freightOrderNbr: raw.freightOrderNbr ?? "—",
    hermPoNbr: raw.hermPoNbr ?? "—",
    euDepId: raw.euDepId ?? "—",
    depOrdrNbr: raw.depOrdrNbr ?? "—",
    shipToAttnFlg: raw.shipToAttnFlg ?? "—",
    custDelStusFlg: raw.custDelStusFlg ?? "—",
    ordrCigId: raw.ordrCigId ?? "—",
    ordrCupId: raw.ordrCupId ?? "—",
    lnFulfillSw: raw.lnFulfillSw ?? "—",
    dpasTypeCd: raw.dpasTypeCd ?? "—",
    dpasPgmId: raw.dpasPgmId ?? "—",
    vendAuthNbr: raw.vendAuthNbr ?? "—",
    futOrdrPromDt: raw.futOrdrPromDt ?? "—",
    prcConcessionTxt: raw.prcConcessionTxt ?? "—",
    prevContNbr: raw.prevContNbr ?? "—",
    contTypeCd: raw.contTypeCd ?? "—",
    termId: raw.termId ?? "—",
    xediRlsdInd: raw.xediRlsdInd ?? "—",
    quoteNbr: raw.quoteNbr ?? "—",
    xediAckFlg: raw.xediAckFlg ?? "—",
    vmfHdrHldInd: raw.vmfHdrHldInd ?? "—",
    hybrdAnntyOrdrInd: raw.hybrdAnntyOrdrInd ?? "—",
    hybrdAnntyCnfmtnId: raw.hybrdAnntyCnfmtnId ?? "—",

    // poNumber: raw.poNumber ?? "—",
    // // countryCode: raw.countryCode ?? "—",
    // partnerId: raw.partnerId ?? "—",
    // custCoCd: raw.custCoCd ?? "—",
    // custBr: raw.custBr ?? "—",
    // custNbr: raw.custNbr ?? "—",
    // custSfx: raw.custSfx ?? "—",
    // imiAsgdBrNbr: raw.imiAsgdBrNbr ?? "—",
    // imiAsgdOrdrNbr: raw.imiAsgdOrdrNbr ?? "—",
    // ordShFr: raw.ordShFr ?? "error",
    // tag: raw.tagNbr ?? "error",
    // holdCode: raw.holdCd ?? " ",
    // termId: raw.termId ?? " ",
    // cmbBtchNbr:raw.cmbBtchNbr ?? " ",
    // stateCd: raw.stateCd ?? " ",
    // imiCarCd:raw.imiCarCd ?? " ",
    // ordSt:raw.ordSt ?? " ",
    // custPoDt: raw.custPoDt ?? " ",

    // // "Order Number" on screen = the IMI-assigned order number.
    // orderNumber: raw.imiAsgdOrdrNbr ?? "—",
    // orderDate: raw.custPoDt ?? null,
    // orderSource: raw.termId ?? "—",
    // currency: raw.ordrCcyCd ?? "USD",
    // totalLineItems: Array.isArray(raw.lineItems) ? raw.lineItems.length : 0,
    // orderTotal: 0,
    // accountNumber: raw.custNbr ?? "—",

    // // Not returned by the backend — EO_ORDR_HDR_INFO only stores numeric
    // // IDs (CUST_NBR, PARTNER_ID), not human-readable names. Shown as
    // // "Not available" in the UI rather than left blank, so it's clear
    // // this is a known gap, not a bug.
    // accountName: raw.accountName ?? null,
    // partnerName: raw.partnerName ?? null,

    // // Not returned by the backend — this is just "when the browser got a
    // // response," not a DB2 timestamp.
    // retrievedAt: new Date().toISOString(),
  };

  const rawLineItems = Array.isArray(raw.lineItems) ? raw.lineItems : [];
  const lineItems = rawLineItems.map((li, i) => ({
    custCoCd: li.custCoCd ?? raw.custCoCd ?? "—",
    custBr: li.custBr ?? raw.custBr ?? "—",
    custNbr: li.custNbr ?? raw.custNbr ?? "—",
    custPoNbr: li.custPoNbr ?? raw.custPoNbr ?? raw.poNumber ?? "—",
    imiLineNbr: li.imiLineNbr ?? li.lineSeqNbr ?? li.line ?? i + 1,
    imiPartNbr: li.imiPartNbr ?? li.sku ?? "—",
    qtyOrdered: Number(li.qtyOrdered ?? li.qty ?? 0),

    custSfx: li.custSfx ?? "—",
    sdqSeqNbr: li.sdqSeqNbr ?? "—",
    custPoDt: li.custPoDt ?? "—",
    custPoSeqNbr: li.custPoSeqNbr ?? "—",
    lineSeqNbr: li.lineSeqNbr ?? "—",
    prtnrLineNbr: li.prtnrLineNbr ?? "—",
    custPartNbr: li.custPartNbr ?? "—",
    mfctrPartNbr: li.mfctrPartNbr ?? "—",
    upcPartNbr: li.upcPartNbr ?? "—",
    custQotdPrc: li.custQotdPrc ?? 0,
    csPkQty: li.csPkQty ?? 0,
    custPartDesc1: li.custPartDesc1 ?? "—",
    custPartDesc2: li.custPartDesc2 ?? "—",
    rsvInvtyFlg: li.rsvInvtyFlg ?? "—",
    imiPartDesc1: li.imiPartDesc1 ?? "—",
    imiPartDesc2: li.imiPartDesc2 ?? "—",
    prcUseFlg: li.prcUseFlg ?? "—",
    lineReqDlvyDt: li.lineReqDlvyDt ?? "—",
    lineReqShipDt: li.lineReqShipDt ?? "—",
    lineReqCancDt: li.lineReqCancDt ?? "—",
    lineBoFlg: li.lineBoFlg ?? "—",
    aggrCd: li.aggrCd ?? "—",
    miscChrgSku: li.miscChrgSku ?? "—",
    assetTagFlg: li.assetTagFlg ?? "—",
    oprtSys: li.oprtSys ?? "—",
    dlvyMthd: li.dlvyMthd ?? "—",
    labType: li.labType ?? "—",
    qtyPerConfig: li.qtyPerConfig ?? 0,
    configQty: li.configQty ?? 0,
    itemTypeInd: li.itemTypeInd ?? "—",
    qtyAlloc: li.qtyAlloc ?? 0,
    endUserPrc: li.endUserPrc ?? 0,
    imiRejCd: li.imiRejCd ?? "—",
    acptRejFlg: li.acptRejFlg ?? "—",
    miscCd: li.miscCd ?? "—",
    lineTypeSw: li.lineTypeSw ?? "—",
    qtyBo: li.qtyBo ?? 0,
    unitPrc: li.unitPrc ?? 0,
    rtlPrc: li.rtlPrc ?? 0,
    frgnUnitPrc: li.frgnUnitPrc ?? 0,
    subPartNbr: li.subPartNbr ?? "—",
    eta: li.eta ?? "—",
    freeItemSw: li.freeItemSw ?? "—",
    vendNbr: li.vendNbr ?? "—",
    lineVlaAuthNbr: li.lineVlaAuthNbr ?? "—",
    euAddrLoc: li.euAddrLoc ?? "—",
    euInfoReqFlg: li.euInfoReqFlg ?? "—",
    busRegnCd: li.busRegnCd ?? "—",
    custSpecHndlCd: li.custSpecHndlCd ?? "—",
    serialNbrFlg: li.serialNbrFlg ?? "—",
    svcAmt: li.svcAmt ?? 0,
    svcQty: li.svcQty ?? 0,
    htImiRejCd: li.htImiRejCd ?? "—",
    etaSrcCd: li.etaSrcCd ?? "—",
    htInitRejCd: li.htInitRejCd ?? "—",
    bidNbr: li.bidNbr ?? "—",
    bidVrsnNbr: li.bidVrsnNbr ?? "—",
    extVendPartNbr: li.extVendPartNbr ?? "—",
    origSpplPartNbr: li.origSpplPartNbr ?? "—",
    hermShipFrBrNbr: li.hermShipFrBrNbr ?? "—",
    hermUnitCostAmt: li.hermUnitCostAmt ?? 0,
    hermUnitPrcAmt: li.hermUnitPrcAmt ?? 0,
    hermLineTypeCd: li.hermLineTypeCd ?? "—",
    hermStusFlg: li.hermStusFlg ?? "—",
    imiRejCdDesc: li.imiRejCdDesc ?? "—",
    lineVmfInfoSw: li.lineVmfInfoSw ?? "—",
    futLinePromDt: li.futLinePromDt ?? "—",
    ctoUnitCostAmt: li.ctoUnitCostAmt ?? 0,
    ctoUnitPrcAmt: li.ctoUnitPrcAmt ?? 0,
    linkId: li.linkId ?? "—",
    euPpPrcAmt: li.euPpPrcAmt ?? 0,
    euPpPurDt: li.euPpPurDt ?? "—",
    termEndDt: li.termEndDt ?? "—",
    quoteLineInd: li.quoteLineInd ?? "—",
    vmfLneHldInd: li.vmfLneHldInd ?? "—",
    imiHoldCd: li.imiHoldCd ?? "—",
  }));

  const toStatusChangeRecord = (entry) => ({
    coCd: entry.coCd ?? entry.CO_CD ?? "—",
    ordrBrNbr: entry.ordrBrNbr ?? entry.ORDR_BR_NBR ?? "—",
    ordrNbr: entry.ordrNbr ?? entry.ORDR_NBR ?? "—",
    distNbr: entry.distNbr ?? entry.DIST_NBR ?? "—",
    shipNbr: entry.shipNbr ?? entry.SHIP_NBR ?? "—",
    ordrDt: entry.ordrDt ?? entry.ORDR_DT ?? "—",
    stusChgTypCd: entry.stusChgTypCd ?? entry.STUS_CHG_TYP_CD ?? "—",
    stusChgTs: entry.stusChgTs ?? entry.STUS_CHG_TS ?? "—",
    ordrLineNbr: entry.ordrLineNbr ?? entry.ORDR_LINE_NBR ?? "—",
    custBrNbr: entry.custBrNbr ?? entry.CUST_BR_NBR ?? "—",
    custNbr: entry.custNbr ?? entry.CUST_NBR ?? "—",
    webProcsFlg: entry.webProcsFlg ?? entry.WEB_PROCS_FLG ?? "—",
    tomcatProcsFlg: entry.tomcatProcsFlg ?? entry.TOMCAT_PROCS_FLG ?? "—",
    ordrChgStusCd: entry.ordrChgStusCd ?? entry.ORDR_CHG_STUS_CD ?? "—",
    configStusCd: entry.configStusCd ?? entry.CONFIG_STUS_CD ?? "—",
    aggregateId: entry.aggregateId ?? entry.AGGREGATE_ID ?? "—",
    prmsChgDt: entry.prmsChgDt ?? entry.PRMS_CHG_DT ?? "—",
    familyCd: entry.familyCd ?? entry.FAMILY_CD ?? "—",
    lstChgProgNam: entry.lstChgProgNam ?? entry.LST_CHG_PROG_NAM ?? "—",
    lstChgOperId: entry.lstChgOperId ?? entry.LST_CHG_OPER_ID ?? "—",
    updtRsnTxt: entry.updtRsnTxt ?? entry.UPDT_RSN_TXT ?? "—",
    evntRsnCd: entry.evntRsnCd ?? entry.EVNT_RSN_CD ?? "—",
    flrDnlQty: entry.flrDnlQty ?? entry.FLR_DNL_QTY ?? "—",
  });

  const rawStatusChanges =
    raw.statusChanges ?? raw.orderStatusChanges ?? raw.orOrderStusChgs ?? [];
  const statusChanges = Array.isArray(rawStatusChanges)
    ? rawStatusChanges
      .filter((entry) => entry && typeof entry === "object" && !Array.isArray(entry))
      .map((entry) => toStatusChangeRecord(entry))
    : [];

  const rawPartnerSetup =
    raw.partnerSetup ?? raw.partnerSetups ?? raw.partnerSetupDetails ?? raw.setupConfig ?? [];
  const setupConfig = Array.isArray(rawPartnerSetup)
    ? rawPartnerSetup.filter((entry) => entry && typeof entry === "object" && !Array.isArray(entry)).map(toPartnerSetupRecord)
    : rawPartnerSetup && typeof rawPartnerSetup === "object"
      ? [toPartnerSetupRecord(rawPartnerSetup)]
      : [];

  const rawInPoSw = raw.inPoSw ?? raw.ieInPoSw ?? raw.poSwitch ?? [];
  const inPoSw = Array.isArray(rawInPoSw)
    ? rawInPoSw
      .filter((entry) => entry && typeof entry === "object" && !Array.isArray(entry))
      .map((entry) => toInPoSwRecord(entry))
    : rawInPoSw && typeof rawInPoSw === "object"
      ? [toInPoSwRecord(rawInPoSw)]
      : [];

  const availableSections = ["orderHeader", "lineItems"];
  if (statusChanges.length > 0) availableSections.push("flowTrace");
  if (setupConfig.length > 0) availableSections.push("setupConfig");
  if (inPoSw.length > 0) availableSections.push("poSwitch");

  // Only these two sections have a real backend data source right now.
  // Flow Trace, Setup Validation, Datadog, and MQ still show "Not
  // available yet" placeholders in the UI — add their keys here once
  // their endpoints exist on the backend.
  return {
    order,
    lineItems,
    processingSteps: [],
    flowTrace: statusChanges,
    setupConfig,
    inPoSw,
    setupValidation: [],
    logs: [],
    datadogAlerts: [],
    mqQueues: [],
    _raw: raw,
    _meta: {
      availableSections,
    },
  };
}
