/**
 * lineItemFieldConfig.js — Single source of truth for all ODS.IMS_ORDER_LINE_ORSLNE fields.
 *
 * Every field returned by OrderLineItem (OrderResponseModel.cs) is listed here.
 * Groups are organized for readability while preserving backend-native key names.
 * Field types mirror fieldConfig.js conventions:
 *   "text"    – plain string
 *   "id"      – monospace + copy-to-clipboard
 *   "number"  – integer / decimal
 *   "date"    – formatDateTime()
 *   "flag"    – "Y" → Enabled (green) | "N" → Disabled (muted)
 *
 * NOTE: custNbr, custPoNbr, custSfx, sdqSeqNbr, custPoDt, custPoSeqNbr are
 * header-level fields injected into each line item by mapOrderResponse.js so
 * the detail page has full context without a separate header fetch.
 */

// ─── Accordion groups — backend-native keys from OrderLineItem ───────────────
export const LINE_ITEM_FIELD_GROUPS = [
  {
    id: "identity",
    label: "Line Identity",
    icon: "Hash",
    defaultOpen: true,
    fields: [
      { key: "companyCd",    label: "COMPANY_CD",       type: "text" },
      { key: "branchNbr",    label: "BRANCH_NBR",       type: "text" },
      { key: "ordrNbr",      label: "ORDR_NBR",         type: "id", copyable: true },
      { key: "distNbr",      label: "DIST_NBR",         type: "text" },
      { key: "shipNbr",      label: "SHIP_NBR",         type: "text" },
      { key: "lineNbr",      label: "LINE_NBR",         type: "id", copyable: true },
      { key: "lineTyp",      label: "LINE_TYP",         type: "text" },
      { key: "lineStus",     label: "LINE_STUS",        type: "text" },
      // Header-level context fields injected by mapOrderResponse.js
      { key: "custNbr",      label: "CUST_NBR",         type: "id", copyable: true },
      { key: "custPoNbr",    label: "CUST_PO_NBR",      type: "id", copyable: true },
      { key: "custSfx",      label: "CUST_SFX",         type: "text" },
      { key: "sdqSeqNbr",    label: "SDQ_SEQ_NBR",      type: "number" },
      { key: "custPoDt",     label: "CUST_PO_DT",       type: "date" },
      { key: "custPoSeqNbr", label: "CUST_PO_SEQ_NBR",  type: "number" },
      { key: "custLineNbr",  label: "CUST_LINE_NBR",    type: "text" },
    ],
  },

  {
    id: "part",
    label: "Part Information",
    icon: "Package",
    defaultOpen: true,
    fields: [
      { key: "imPartNbr",      label: "IM_PART_NBR",       type: "id", copyable: true },
      { key: "custItemNbr",    label: "CUST_ITEM_NBR",     type: "id", copyable: true },
      { key: "vendPartNbr",    label: "VEND_PART_NBR",     type: "id", copyable: true },
      { key: "upcNbr",         label: "UPC_NBR",           type: "text" },
      { key: "des",            label: "DES",               type: "text" },
      { key: "xtraDesSw",      label: "XTRA_DES_SW",       type: "flag" },
      { key: "itemTyp",        label: "ITEM_TYP",          type: "text" },
      { key: "catNbr",         label: "CAT_NBR",           type: "text" },
      { key: "vendNbr",        label: "VEND_NBR",          type: "id", copyable: true },
      { key: "cntryOfOrig",    label: "CNTRY_OF_ORIG",     type: "text" },
      { key: "commodCode",     label: "COMMOD_CODE",       type: "text" },
      { key: "expLicence",     label: "EXP_LICENCE",       type: "text" },
    ],
  },

  {
    id: "quantities",
    label: "Quantities",
    icon: "BarChart2",
    fields: [
      { key: "qtyOrded",      label: "QTY_ORDED",        type: "number" },
      { key: "qtyBord",       label: "QTY_BORD",         type: "number" },
      { key: "qtyShpd",       label: "QTY_SHPD",         type: "number" },
      { key: "qtyBild",       label: "QTY_BILD",         type: "number" },
      { key: "allocResvQty",  label: "ALLOC_RESV_QTY",   type: "number" },
      { key: "compQtyPer",    label: "COMP_QTY_PER",     type: "number" },
      { key: "lsbQtyAvail",   label: "LSB_QTY_AVAIL",    type: "number" },
      { key: "rmaQtyOpen",    label: "RMA_QTY_OPEN",     type: "number" },
      { key: "rmaRecvToday",  label: "RMA_RECV_TODAY",   type: "number" },
      { key: "um",            label: "UM",               type: "text" },
      { key: "baseUm",        label: "BASE_UM",          type: "text" },
      { key: "baseUnit",      label: "BASE_UNIT",        type: "text" },
    ],
  },

  {
    id: "pricing",
    label: "Pricing",
    icon: "DollarSign",
    fields: [
      { key: "cusOrigUnitPrc",      label: "CUS_ORIG_UNIT_PRC",      type: "number" },
      { key: "unitPriceReseller",   label: "UNIT_PRICE_RESELLER",    type: "number" },
      { key: "unitPrc",             label: "UNIT_PRC",               type: "number" },
      { key: "unitCost",            label: "UNIT_COST",              type: "number" },
      { key: "retailPrice",         label: "RETAIL_PRICE",           type: "number" },
      { key: "invUnitCost",         label: "INV_UNIT_COST",          type: "number" },
      { key: "convBasePrice",       label: "CONV_BASE_PRICE",        type: "number" },
      { key: "configUnitPrice",     label: "CONFIG_UNIT_PRICE",      type: "number" },
      { key: "orlForeignUnitPrice", label: "ORL_FOREIGN_UNIT_PRICE", type: "number" },
      { key: "orlActualExchgRate",  label: "ORL_ACTUAL_EXCHG_RATE",  type: "number" },
      { key: "orlVdrExchgRate",     label: "ORL_VDR_EXCHG_RATE",     type: "number" },
      { key: "adjCost",             label: "ADJ_COST",               type: "number" },
      { key: "origAdjCost",         label: "ORIG_ADJ_COST",          type: "number" },
      { key: "altUnitCost",         label: "ALT_UNIT_COST",          type: "number" },
      { key: "sbstutCost",          label: "SBSTUT_COST",            type: "number" },
      { key: "specialSystemsCost",  label: "SPECIAL_SYSTEMS_COST",   type: "number" },
      { key: "frtInAmtBild",        label: "FRT_IN_AMT_BILD",        type: "number" },
      { key: "frtOutAmtBild",       label: "FRT_OUT_AMT_BILD",       type: "number" },
      { key: "rebatAmt",            label: "REBAT_AMT",              type: "number" },
      { key: "tradeDisc",           label: "TRADE_DISC",             type: "number" },
      { key: "discPct",             label: "DISC_PCT",               type: "number" },
      { key: "discCd",              label: "DISC_CD",                type: "text" },
      { key: "frgnUnitPrcSemi",     label: "FRGN_UNIT_PRC_SEMI",     type: "number" },
      { key: "reqPrftPct",          label: "REQ_PRFT_PCT",           type: "number" },
    ],
  },

  {
    id: "dates",
    label: "Dates & Delivery",
    icon: "Calendar",
    fields: [
      { key: "entyDt",      label: "ENTY_DT",        type: "date" },
      { key: "entryTime",   label: "ENTRY_TIME",     type: "text" },
      { key: "prmsDt",      label: "PRMS_DT",        type: "date" },
      { key: "cancDt",      label: "CANC_DT",        type: "date" },
      { key: "boEtaDate",   label: "BO_ETA_DATE",    type: "date" },
      { key: "lastChgTime", label: "LAST_CHG_TIME",  type: "text" },
      { key: "lstChgDt",    label: "LST_CHG_DT",     type: "date" },
      { key: "odsLstUpdDt", label: "ODS_LST_UPD_DT", type: "date" },
    ],
  },

  {
    id: "flags",
    label: "Flags & Controls",
    icon: "AlertCircle",
    fields: [
      { key: "bordrSw",           label: "BORDR_SW",            type: "flag" },
      { key: "reserveTypeSw",     label: "RESERVE_TYPE_SW",     type: "text" },
      { key: "freeItemSw",        label: "FREE_ITEM_SW",        type: "flag" },
      { key: "serialNbrAvailSw",  label: "SERIAL_NBR_AVAIL_SW", type: "flag" },
      { key: "asetTagSw",         label: "ASET_TAG_SW",         type: "flag" },
      { key: "holdCode",          label: "HOLD_CODE",           type: "text" },
      { key: "aggregateCode",     label: "AGGREGATE_CODE",      type: "text" },
      { key: "mchgCd",            label: "MCHG_CD",             type: "text" },
      { key: "invInd",            label: "INV_IND",             type: "flag" },
      { key: "colInd",            label: "COL_IND",             type: "flag" },
      { key: "mcOrideSw",         label: "MC_ORIDE_SW",         type: "flag" },
      { key: "umOrideSw",         label: "UM_ORIDE_SW",         type: "flag" },
      { key: "upOrideSw",         label: "UP_ORIDE_SW",         type: "flag" },
      { key: "ucOrideSw",         label: "UC_ORIDE_SW",         type: "flag" },
      { key: "sysCmpntSw",        label: "SYS_CMPNT_SW",        type: "flag" },
      { key: "cnsgmInvSw",        label: "CNSGM_INV_SW",        type: "flag" },
      { key: "rollSw",            label: "ROLL_SW",             type: "flag" },
      { key: "adjdCostSw",        label: "ADJD_COST_SW",        type: "flag" },
      { key: "itemCnsndSw",       label: "ITEM_CNSND_SW",       type: "flag" },
      { key: "acopCostOrideInd",  label: "ACOP_COST_ORIDE_IND", type: "flag" },
      { key: "acopRprcSw",        label: "ACOP_RPRC_SW",        type: "flag" },
      { key: "maqInd",            label: "MAQ_IND",             type: "flag" },
      { key: "govtBidBasedLineSw",label: "GOVT_BID_BASED_LINE_SW", type: "flag" },
      { key: "alncSw",            label: "ALNC_SW",             type: "flag" },
      { key: "bohUpdOnlineSw",    label: "BOH_UPD_ONLINE_SW",   type: "flag" },
      { key: "coopFlg",           label: "COOP_FLG",            type: "flag" },
      { key: "rvsAcopInd",        label: "RVS_ACOP_IND",        type: "flag" },
      { key: "semiCnducSw",       label: "SEMI_CNDUC_SW",       type: "flag" },
      { key: "shtInd",            label: "SHT_IND",             type: "flag" },
      { key: "slsTypSw",          label: "SLS_TYP_SW",          type: "flag" },
      { key: "specCompInd",       label: "SPEC_COMP_IND",       type: "flag" },
      { key: "txblItemSw",        label: "TXBL_ITEM_SW",        type: "flag" },
      { key: "usysContAcopInd",   label: "USYS_CONT_ACOP_IND",  type: "flag" },
      { key: "nonStdConvSw",      label: "NON_STD_CONV_SW",     type: "flag" },
      { key: "aapBuildInd",       label: "AAP_BUILD_IND",       type: "flag" },
      { key: "acopDeltaPrcInd",   label: "ACOP_DELTA_PRC_IND",  type: "flag" },
    ],
  },

  {
    id: "technical",
    label: "Technical",
    icon: "Truck",
    fields: [
      { key: "configurationLab",  label: "CONFIGURATION_LAB",   type: "text" },
      { key: "cfgLab",            label: "CFG_LAB",             type: "text" },
      { key: "cfgInd",            label: "CFG_IND",             type: "text" },
      { key: "configInd",         label: "CONFIG_IND",          type: "text" },
      { key: "configId",          label: "CONFIG_ID",           type: "text" },
      { key: "configAssemblyCd",  label: "CONFIG_ASSEMBLY_CD",  type: "text" },
      { key: "systemItemLineNbr", label: "SYSTEM_ITEM_LINE_NBR",type: "text" },
      { key: "relatedGovtBidVsn", label: "RELATED_GOVT_BID_VSN",type: "text" },
      { key: "relatedGovtBidGsn", label: "RELATED_GOVT_BID_GSN",type: "text" },
      { key: "altWhseBr",         label: "ALT_WHSE_BR",         type: "text" },
      { key: "altWhseCo",         label: "ALT_WHSE_CO",         type: "text" },
      { key: "altWhseCcy",        label: "ALT_WHSE_CCY",        type: "text" },
      { key: "vdrExchgRtTyp",     label: "VDR_EXCHG_RT_TYP",    type: "text" },
      { key: "faastSapInvcNbr",   label: "FAAST_SAP_INVC_NBR",  type: "text" },
      { key: "unitWgt",           label: "UNIT_WGT",            type: "number" },
      { key: "wgtPer",            label: "WGT_PER",             type: "number" },
      { key: "cfscmpSysItemCo",   label: "CFSCMP_SYS_ITEM_CO",  type: "text" },
      { key: "cfscmpSysItemNbr",  label: "CFSCMP_SYS_ITEM_NBR", type: "text" },
      { key: "allocType",         label: "ALLOC_TYPE",          type: "text" },
      { key: "invoiceBreakCode",  label: "INVOICE_BREAK_CODE",  type: "text" },
      { key: "reserveSeqNbr",     label: "RESERVE_SEQ_NBR",     type: "text" },
      { key: "splitBillToSuff",   label: "SPLIT_BILL_TO_SUFF",  type: "text" },
      { key: "cuaShipFrom",       label: "CUA_SHIP_FROM",       type: "text" },
    ],
  },

  {
    id: "tax",
    label: "Tax & Financial",
    icon: "Receipt",
    fields: [
      { key: "terms",         label: "TERMS",            type: "text" },
      { key: "taxCd",         label: "TAX_CD",           type: "text" },
      { key: "vatTaxCd",      label: "VAT_TAX_CD",       type: "text" },
      { key: "vatTaxRt",      label: "VAT_TAX_RT",       type: "number" },
      { key: "icmsCode",      label: "ICMS_CODE",        type: "text" },
      { key: "icmsTaxAmt",    label: "ICMS_TAX_AMT",     type: "number" },
      { key: "icmsTaxRate",   label: "ICMS_TAX_RATE",    type: "number" },
      { key: "ipiIssTaxSw",   label: "IPI_ISS_TAX_SW",   type: "flag" },
      { key: "ipiIssTaxAmt",  label: "IPI_ISS_TAX_AMT",  type: "number" },
      { key: "ipiIssTaxRate", label: "IPI_ISS_TAX_RATE", type: "number" },
      { key: "pcTaxAmt",      label: "PC_TAX_AMT",       type: "number" },
      { key: "tesCode",       label: "TES_CODE",         type: "text" },
    ],
  },

  {
    id: "transfer",
    label: "Transfer & Inventory",
    icon: "ArrowRightLeft",
    fields: [
      { key: "trToBrNbr",      label: "TR_TO_BR_NBR",    type: "text" },
      { key: "trToDistNbr",    label: "TR_TO_DIST_NBR",  type: "text" },
      { key: "trToOrdrNbr",    label: "TR_TO_ORDR_NBR",  type: "text" },
      { key: "trToShipNbr",    label: "TR_TO_SHIP_NBR",  type: "text" },
      { key: "inStkBr",        label: "IN_STK_BR",       type: "number" },
      { key: "inStkOth",       label: "IN_STK_OTH",      type: "number" },
      { key: "lsb",            label: "LSB",             type: "text" },
      { key: "keyBr",          label: "KEY_BR",          type: "text" },
      { key: "keyCo",          label: "KEY_CO",          type: "text" },
      { key: "rmaOvergoodsCd", label: "RMA_OVERGOODS_CD",type: "text" },
    ],
  },

  {
    id: "salesRef",
    label: "Sales & Reference",
    icon: "User",
    fields: [
      { key: "osSlsmn",           label: "OS_SLSMN",            type: "text" },
      { key: "isSlsmn",           label: "IS_SLSMN",            type: "text" },
      { key: "acopEndUserNbr",    label: "ACOP_END_USER_NBR",   type: "id", copyable: true },
      { key: "promoCd",           label: "PROMO_CD",            type: "text" },
      { key: "refdirOverrideText",label: "REFDIR_OVERRIDE_TEXT",type: "text" },
      { key: "refdirOvrdTyp",     label: "REFDIR_OVRD_TYP",     type: "text" },
      { key: "ossNo",             label: "OSS_NO",              type: "text" },
      { key: "pgmTyp1",           label: "PGM_TYP_1",           type: "text" },
      { key: "pgmTyp2",           label: "PGM_TYP_2",           type: "text" },
      { key: "lastChgOpid",       label: "LAST_CHG_OPID",       type: "text" },
    ],
  },
];
